# Generated by Django 4.1.5 on 2023-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avddisk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Имя'),
        ),
    ]
